// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-BR7B6w-kZARb7Nr3WF5NC-EP8cfOUTY',
    appId: '1:297140807930:web:95d9c8500b0b34ac370143',
    messagingSenderId: '297140807930',
    projectId: 'cinx-d9301',
    authDomain: 'cinx-d9301.firebaseapp.com',
    storageBucket: 'cinx-d9301.firebasestorage.app',
    measurementId: 'G-LC815R1MCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7a29AdXkbUC7OQIPfHXtTyAy8ePC-sFk',
    appId: '1:297140807930:android:3d3900f16f06d167370143',
    messagingSenderId: '297140807930',
    projectId: 'cinx-d9301',
    storageBucket: 'cinx-d9301.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKZCc9RPLruyzM-dbRMtk94VwwgDsLSGQ',
    appId: '1:297140807930:ios:5a36abd4b5cac809370143',
    messagingSenderId: '297140807930',
    projectId: 'cinx-d9301',
    storageBucket: 'cinx-d9301.firebasestorage.app',
    iosBundleId: 'com.example.cinx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKZCc9RPLruyzM-dbRMtk94VwwgDsLSGQ',
    appId: '1:297140807930:ios:5a36abd4b5cac809370143',
    messagingSenderId: '297140807930',
    projectId: 'cinx-d9301',
    storageBucket: 'cinx-d9301.firebasestorage.app',
    iosBundleId: 'com.example.cinx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-BR7B6w-kZARb7Nr3WF5NC-EP8cfOUTY',
    appId: '1:297140807930:web:9dfc7a37f9878592370143',
    messagingSenderId: '297140807930',
    projectId: 'cinx-d9301',
    authDomain: 'cinx-d9301.firebaseapp.com',
    storageBucket: 'cinx-d9301.firebasestorage.app',
    measurementId: 'G-SWQWX5HQXL',
  );
}
